apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-basics
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: projectdevops.eu
    http:
      paths:
      - backend:
          service:
            name: php-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: grafana.projectdevops.eu
    http:
      paths:
      - backend:
          service:
            name: my-grafana
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: prometheus.projectdevops.eu
    http:
      paths:
      - backend:
          service:
            name: prometheus-server
            port:
              number: 80
        path: /
        pathType: Prefix


              
