apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: production
spec:
  interval: 1m
  chart:
    spec:
      chart: ./apps/base/prometheus/prometheus-app/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
